rename ALPAKA_INTEGRATION_TEST to ALPAKA_CI

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -42,14 +42,15 @@ compiler:
 
 ################################################################################
 # \TODO: Test full matrix:
-# ALPAKA_INTEGRATION_TEST                       : {ON}
 # CXX                                           : {g++, clang++}
 #   [clang++] ALPAKA_CLANG_LIBSTDCPP_VERSION    : {4.9}
-#   [clang++] ALPAKA_CLANG_VER                  : {3.5, 3.6, 3.7, 3.8}
+#   [clang++] ALPAKA_CLANG_VER                  : {3.5, 3.6, 3.7, 3.8, 3.9}
 #   [g++] ALPAKA_GCC_VER                        : {4.9, 5}
-# ALPAKA_BOOST_BRANCH                           : {boost-1.59.0, boost-1.60.0, develop}
-# ALPAKA_CMAKE_VER                              : {3.3.2, 3.4.3}
 # CMAKE_BUILD_TYPE                              : {Debug, Release}
+# ALPAKA_CI                                     : {ON}
+# ALPAKA_CI_BOOST_BRANCH                        : {boost-1.59.0, boost-1.60.0, develop}
+# ALPAKA_CI_CMAKE_VER                           : {3.3.2, 3.4.3}
+# ALPAKA_CI_ANALYSIS                            : {ON, OFF}
 # ALPAKA_DEBUG                                  : {0, 1, 2}
 # ALPAKA_ACC_CPU_B_SEQ_T_SEQ_ENABLE             : {ON, OFF}
 # ALPAKA_ACC_CPU_B_SEQ_T_THREADS_ENABLE         : {ON, OFF}
@@ -62,8 +63,6 @@ compiler:
 #   [ON] OMP_NUM_THREADS                        : {1, 2, 3, 4}
 # ALPAKA_ACC_GPU_CUDA_ENABLE                    : {ON, OFF}
 #   [ON] ALPAKA_CUDA_VERSION                    : {7.0, 7.5}
-# And one analysis build
-# ALPAKA_ANALYSIS                               : {ON, OFF}
 ################################################################################
 env:
     global:
@@ -77,32 +76,32 @@ env:
 
     matrix:
         # Analysis builds
-        - ALPAKA_CUDA_VERSION=7.5 ALPAKA_ANALYSIS=ON  ALPAKA_DEBUG=2 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.7 ALPAKA_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
-        - ALPAKA_CUDA_VERSION=7.5 ALPAKA_ANALYSIS=ON  ALPAKA_DEBUG=2 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.7 ALPAKA_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
+        - ALPAKA_CUDA_VERSION=7.5 ALPAKA_CI_ANALYSIS=ON  ALPAKA_DEBUG=2 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.7 ALPAKA_CI_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
+        - ALPAKA_CUDA_VERSION=7.5 ALPAKA_CI_ANALYSIS=ON  ALPAKA_DEBUG=2 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.7 ALPAKA_CI_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
 
         # Debug builds
-        - ALPAKA_CUDA_VERSION=7.5 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CMAKE_VER=3.3.2 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.8 ALPAKA_BOOST_BRANCH=boost-1.59.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
-        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=0 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=3 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.5 ALPAKA_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
-        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CMAKE_VER=3.3.2 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=2 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.6 ALPAKA_BOOST_BRANCH=boost-1.59.0 ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
-        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
+        - ALPAKA_CUDA_VERSION=7.5 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CI_CMAKE_VER=3.3.2 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.8 ALPAKA_CI_BOOST_BRANCH=boost-1.59.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
+        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=0 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=3 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.5 ALPAKA_CI_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
+        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CI_CMAKE_VER=3.3.2 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=2 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.6 ALPAKA_CI_BOOST_BRANCH=boost-1.59.0 ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
+        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_CI_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
 
         # Release builds
-        # FIXME: Reenable Release builds for CUDA. Currently Debug is used because BOOST_AUTO_TEST_CASE_TEMPLATE does not compile in Release mode.
-        #- ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CMAKE_VER=3.3.2 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=4 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.8 ALPAKA_BOOST_BRANCH=boost-1.59.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
-        #- ALPAKA_CUDA_VERSION=7.5 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=0 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=3 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.5 ALPAKA_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
-        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=0 ALPAKA_CMAKE_VER=3.4.2 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=2 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.5 ALPAKA_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
-        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
+        # FIXME: Reenable Release builds for CUDA. BOOST_AUTO_TEST_CASE_TEMPLATE does not compile in Release mode.
+        #- ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CI_CMAKE_VER=3.3.2 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=4 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.8 ALPAKA_CI_BOOST_BRANCH=boost-1.59.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
+        #- ALPAKA_CUDA_VERSION=7.5 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=0 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=3 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.6 ALPAKA_CI_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=ON
+        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=0 ALPAKA_CI_CMAKE_VER=3.4.2 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=2 ALPAKA_GCC_VER=4.9 ALPAKA_CLANG_VER=3.5 ALPAKA_CI_BOOST_BRANCH=boost-1.60.0 ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
+        - ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_CI_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
 
 matrix:
     allow_failures:
         - compiler: gcc
-          env: ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
+          env: ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_CI_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
         - compiler: gcc
-          env: ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
+          env: ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_CI_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
         - compiler: clang
-          env: ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
+          env: ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Debug   OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_CI_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
         - compiler: clang
-          env: ALPAKA_CUDA_VERSION=7.0 ALPAKA_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
+          env: ALPAKA_CUDA_VERSION=7.0 ALPAKA_CI_ANALYSIS=OFF ALPAKA_DEBUG=1 ALPAKA_CI_CMAKE_VER=3.4.3 CMAKE_BUILD_TYPE=Release OMP_NUM_THREADS=4 ALPAKA_GCC_VER=5   ALPAKA_CLANG_VER=3.9 ALPAKA_CI_BOOST_BRANCH=develop      ALPAKA_ACC_GPU_CUDA_ENABLE=OFF
 
         - os: osx
 
@@ -154,12 +153,12 @@ install:
 
     #-------------------------------------------------------------------------------
     # Install sloc
-    - if [ "${ALPAKA_ANALYSIS}" == "ON" ] ;then travis_retry sudo apt-get install sloccount ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "ON" ] ;then travis_retry sudo apt-get install sloccount ;fi
 
     #-------------------------------------------------------------------------------
     # Install cppcheck
     # FIXME: Use a better static analysis tool. cppcheck does not support c++11 correctly.
-    #- if [ "${ALPAKA_ANALYSIS}" == "ON" ] ;then travis_retry sudo apt-get install cppcheck ;fi
+    #- if [ "${ALPAKA_CI_ANALYSIS}" == "ON" ] ;then travis_retry sudo apt-get install cppcheck ;fi
 
     #-------------------------------------------------------------------------------
     # Get the current gcc version.
@@ -331,14 +330,14 @@ install:
     # Remove the old version.
     - sudo apt-get -y remove cmake
     # Extract the version numbers.
-    - ALPAKA_CMAKE_VER_MAJOR=${ALPAKA_CMAKE_VER:0:1}
+    - ALPAKA_CMAKE_VER_MAJOR=${ALPAKA_CI_CMAKE_VER:0:1}
     - echo ${ALPAKA_CMAKE_VER_MAJOR}
-    - ALPAKA_CMAKE_VER_MINOR=${ALPAKA_CMAKE_VER:2:1}
+    - ALPAKA_CMAKE_VER_MINOR=${ALPAKA_CI_CMAKE_VER:2:1}
     - echo ${ALPAKA_CMAKE_VER_MINOR}
-    - ALPAKA_CMAKE_PKG_FILE_NAME=cmake-${ALPAKA_CMAKE_VER}-Linux-x86_64
+    - ALPAKA_CMAKE_PKG_FILE_NAME=cmake-${ALPAKA_CI_CMAKE_VER}-Linux-x86_64
     - wget http://www.cmake.org/files/v${ALPAKA_CMAKE_VER_MAJOR}.${ALPAKA_CMAKE_VER_MINOR}/${ALPAKA_CMAKE_PKG_FILE_NAME}.tar.gz
       && tar -xzf ${ALPAKA_CMAKE_PKG_FILE_NAME}.tar.gz
-      && sudo cp -fR cmake-${ALPAKA_CMAKE_VER}-Linux-x86_64/* /usr
+      && sudo cp -fR cmake-${ALPAKA_CI_CMAKE_VER}-Linux-x86_64/* /usr
       && sudo rm -rf ${ALPAKA_CMAKE_PKG_FILE_NAME}.tar.gz ${ALPAKA_CMAKE_PKG_FILE_NAME}
 
     #-------------------------------------------------------------------------------
@@ -346,14 +345,14 @@ install:
     # If fibers are enabled we need boost develop branch.
     - if [ "${ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE}" == "ON" ]
       ;then
-          if [ "${ALPAKA_BOOST_BRANCH}" != "develop" ]
+          if [ "${ALPAKA_CI_BOOST_BRANCH}" != "develop" ]
           ;then
               export ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE=OFF
               && echo ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE=${ALPAKA_ACC_CPU_B_SEQ_T_FIBERS_ENABLE} set because boost fibers requires boost develop branch!
           ;fi
       ;fi
 
-    - git clone -b ${ALPAKA_BOOST_BRANCH} --recursive --single-branch --depth 1 https://github.com/boostorg/boost.git boost
+    - git clone -b ${ALPAKA_CI_BOOST_BRANCH} --recursive --single-branch --depth 1 https://github.com/boostorg/boost.git boost
     - cd boost/
     - export ALPAKA_BOOST_ROOT_DIR=`pwd`
     - echo "ALPAKA_BOOST_ROOT_DIR=${ALPAKA_BOOST_ROOT_DIR}"
@@ -443,27 +442,27 @@ before_script:
 script:
     #-------------------------------------------------------------------------------
     # sloc
-    - if [ "${ALPAKA_ANALYSIS}" == "ON" ] ;then sloccount . ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "ON" ] ;then sloccount . ;fi
 
     #-------------------------------------------------------------------------------
     # TODO/FIXME/HACK
-    - if [ "${ALPAKA_ANALYSIS}" == "ON" ] ;then grep -r HACK * ;fi || true
-    - if [ "${ALPAKA_ANALYSIS}" == "ON" ] ;then grep -r FIXME * ;fi || true
-    - if [ "${ALPAKA_ANALYSIS}" == "ON" ] ;then grep -r TODO * ;fi || true
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "ON" ] ;then grep -r HACK * ;fi || true
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "ON" ] ;then grep -r FIXME * ;fi || true
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "ON" ] ;then grep -r TODO * ;fi || true
 
     #-------------------------------------------------------------------------------
     # cppcheck
     #  --inline-suppr
     # Once only with errors returning a failure on error.
-    #- if [ "${ALPAKA_ANALYSIS}" == "ON" ] ;then cppcheck --force --verbose --error-exitcode=1 -j2 vectorAdd/src/ matMul/src/ sharedMem/src/ mandelbrot/src/ ;fi
+    #- if [ "${ALPAKA_CI_ANALYSIS}" == "ON" ] ;then cppcheck --force --verbose --error-exitcode=1 -j2 vectorAdd/src/ matMul/src/ sharedMem/src/ mandelbrot/src/ ;fi
     # Once with warnings but no failure return code.
-    #- if [ "${ALPAKA_ANALYSIS}" == "ON" ] ;then cppcheck --force --verbose --enable=all -j2 vectorAdd/src/ matMul/src/ sharedMem/src/ mandelbrot/src/ ;fi
+    #- if [ "${ALPAKA_CI_ANALYSIS}" == "ON" ] ;then cppcheck --force --verbose --enable=all -j2 vectorAdd/src/ matMul/src/ sharedMem/src/ mandelbrot/src/ ;fi
 
     #-------------------------------------------------------------------------------
     # analysis
-    #- if [ "${ALPAKA_ANALYSIS}" == "ON" -a "${CXX}" == "clang++" ] ;then export CCC_CC=clang ;fi
-    #- if [ "${ALPAKA_ANALYSIS}" == "ON" -a "${CXX}" == "clang++" ] ;then export CCC_CXX=clang++ ;fi
-    #- if [ "${ALPAKA_ANALYSIS}" == "ON" -a "${CXX}" == "clang++" ]
+    #- if [ "${ALPAKA_CI_ANALYSIS}" == "ON" -a "${CXX}" == "clang++" ] ;then export CCC_CC=clang ;fi
+    #- if [ "${ALPAKA_CI_ANALYSIS}" == "ON" -a "${CXX}" == "clang++" ] ;then export CCC_CXX=clang++ ;fi
+    #- if [ "${ALPAKA_CI_ANALYSIS}" == "ON" -a "${CXX}" == "clang++" ]
     #  ;then
     #      cd mandelbrot/
     #      && mkdir build/
@@ -482,33 +481,32 @@ script:
     #      && scan-build -analyze-headers --status-bugs make VERBOSE=1
     #      && cd ../../../
     #  ;fi
-
-    - if [ "${ALPAKA_ANALYSIS}" == "ON" ] ;then ./travis/compileExec.sh "test/analysis/headerCheck/" ./headerCheck ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "ON" ] ;then ./travis/compileExec.sh "test/analysis/headerCheck/" ./headerCheck ;fi
 
     #-------------------------------------------------------------------------------
     # Build and execute all unit tests.
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/acc/" ./acc ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/atomic/" ./atomic ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/block/shared/" ./blockShared ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/kernel/" ./kernel ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/mem/buf/" ./memBuf ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/mem/view/" ./memView ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/meta/" ./meta ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/time/" ./time ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/vec/" ./vec ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/acc/" ./acc ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/atomic/" ./atomic ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/block/shared/" ./blockShared ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/kernel/" ./kernel ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/mem/buf/" ./memBuf ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/mem/view/" ./memView ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/meta/" ./meta ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/time/" ./time ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/unit/vec/" ./vec ;fi
 
     #-------------------------------------------------------------------------------
     # Build and execute all integration tests.
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/integ/axpy/" ./axpy ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/integ/mandelbrot/" ./mandelbrot ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/integ/matMul/" ./matMul ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/integ/sharedMem/" ./sharedMem ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/integ/axpy/" ./axpy ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/integ/mandelbrot/" ./mandelbrot ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/integ/matMul/" ./matMul ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "test/integ/sharedMem/" ./sharedMem ;fi
 
     #-------------------------------------------------------------------------------
     # Build and execute all examples.
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "example/bufferCopy" ./bufferCopy ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "example/helloWorld" ./helloWorld ;fi
-    - if [ "${ALPAKA_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "example/vectorAdd" ./vectorAdd ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "example/bufferCopy" ./bufferCopy ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "example/helloWorld" ./helloWorld ;fi
+    - if [ "${ALPAKA_CI_ANALYSIS}" == "OFF" ] ;then ./travis/compileExec.sh "example/vectorAdd" ./vectorAdd ;fi
 
 
 ################################################################################
